module.exports.userController = require('./userController')
module.exports.adminUserAuthController = require('./adminUserAuthController')
module.exports.customerAuthController = require('./customerAuthController')
module.exports.productController = require('./productController')
module.exports.orderController = require('./orderController')
module.exports.newsletterController = require('./newsletterController')
